--Tables Creation
CREATE TABLE departments (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             name VARCHAR(255) NOT NULL,
                             code VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE employees (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(255) NOT NULL,
                           email VARCHAR(255) NOT NULL UNIQUE,
                           salary NUMERIC(15,2) NOT NULL,
                           joining_date DATE NOT NULL,
                           department_id INTEGER NOT NULL REFERENCES departments(id)
);

--Mock Data Insertion
INSERT INTO departments (name, code) VALUES
                                         ('Human Resources', 'HR01'),
                                         ('Sales', 'SA01'),
                                         ('Engineering', 'EN01');

INSERT INTO employees (name, email, salary, joining_date, department_id) VALUES
                                                                             ('Alice Johnson', 'alice@example.com', 75000.00, '2018-04-15', 1),
                                                                             ('Bob Smith', 'bob@example.com', 65000.00, '2020-09-10', 2),
                                                                             ('Charlie Davis', 'charlie@example.com', 90000.00, '2015-01-05', 3),
                                                                             ('Dana Lee', 'dana@example.com', 120000.00, '2012-06-20', 3);


